name: $(Date:dd-MM-yyyy)$(Rev:.r)
trigger:
- master
- release/*

pr:
- master
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'samitkumarpatel/msword-templating-fileexplorer-api'
  containerRegistryServiceConnection: 'hub.docker.com'
  tags: |
      latest
      $(Build.BuildNumber)
      
jobs:  
- job: DockerBuildAndPush
  steps:
  - bash: ls -alGh
    displayName: Workspace ls
  - bash: ./mvnw --batch-mode clean install
    displayName: maven build
  - task: Docker@2
    displayName: "Docker Build"
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      containerRegistry: $(containerRegistryServiceConnection)
      repository: $(imageName)
      tags: $(tags)
  - task: Docker@2
    displayName: "Docker Push"
    inputs: 
      command: push
      containerRegistry: $(containerRegistryServiceConnection)
      repository: $(imageName)
      tags: $(tags)
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
